FROM bolderiz/oracle-xe-21c

COPY ./docker/dev/database/sql/create_user.sql /opt/oracle/scripts/startup/create_user.sql
COPY ./docker/dev/database/sql/create_tablespace.sql /opt/oracle/scripts/startup/create_tablespace.sql