name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - django>=3.2.*, <4.0
  - django-environ
  - django-debug-toolbar
  - djangorestframework
  - whitenoise
  - faktory
  - pip
  - pip:
    - gunicorn